apiVersion: v2
name: template-service
description: Krateo PlatformOps Template Service
type: application
icon: "https://github.com/krateoplatformops/community/blob/main/logos/black/icon.svg"

version: VERSION
appVersion: VERSION

dependencies:
  - name: helm-chart-library
    version: 0.1.3
    repository: http://charts.krateo.io

maintainers:
  - name: Mauro Sala
    email: mauro.sala@kiratech.it
    url: https://krateo.io
  - name: Luca Sepe
    email: luca.sepe@kiratech.it
    url: https://www.kiratech.it
