apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ include "helm.serviceAccountName" . }}
  labels:
    {{- include "helm.labels" . | nindent 8 }}
rules:
  - apiGroups: ["templates.krateo.io"]
    resources: ["*"]
    verbs: ["*"]