apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "helm.serviceAccountName" . }}
  labels:
    {{- include "helm.labels" . | nindent 8 }}
rules:
  - apiGroups: ["modules.krateo.io"]
    resources: ["*"]
    verbs: ["*"]
  
  - apiGroups: ["templates.krateo.io"]
    resources: ["*"]
    verbs: ["*"]

  - apiGroups: ["pkg.crossplane.io"]
    resources: ["configurations"]
    verbs: ["list", "get", "create", "delete", "update", "watch"]
  
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "watch", "list"]

  - apiGroups: ["apiextensions.k8s.io"]
    resources: ["customresourcedefinitions"]
    verbs: ["*"]