apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: template-ingress
  labels:
  annotations:
    kubernetes.io/ingress.class: 'kong'
spec:
  rules:
    - host: {{ .Values.template.host }}
      http:
        paths:
          - path: /*
            pathType: Prefix
            backend:
              service:
                name: template-svc
                port:
                  number: 80
